title: Facebook Messenger for WordPress
description: Facebook Messenger live chat on your website! Very easy to use plugin that adds chat on your WordPress site. It supports language change and is integrated with PolyLang. In addition, you can change the position and display of the chatbox
show_downloads: true
theme: jekyll-theme-cayman
